<a href="https://colab.research.google.com/github/FiyinfobaO/Hamoye/blob/master/stage_c_quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv'
df = pd.read_csv(url)
print(df.head(10))

       tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable
5  6.999209  9.109247  3.784066  ...  0.469931 -0.017385    stable
6  6.710166  3.765204  6.929314  ...  0.376630  0.005954  unstable
7  6.953512  1.379125  5.719400  ...  0.380544  0.016634  unstable
8  4.689852  4.007747  1.478573  ...  0.482439 -0.038677    stable
9  9.841496  1.413822  9.769856  ...  0.116263  0.012383  unstable

[10 rows x 14 columns]


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [4]:
# to see no of null values
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [5]:
# dropping the stab column
df = df.drop('stab', axis=1)
df.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1  9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2  8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3  0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4  3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable

[5 rows x 13 columns]

In [6]:
#checking distribution of target variable again
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [7]:
# assigning features, X
X = df.drop(columns='stabf').values
# assigning label/target varaible
y = df[['stabf']].values

In [8]:
#split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print('Train set: ', x_train.shape, y_train.shape)
print('Test set: ', x_test.shape, y_test.shape)

Train set:  (8000, 12) (8000, 1)
Test set:  (2000, 12) (2000, 1)


In [9]:
# scaling the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(x_train, y_train)
sc.transform(x_test)

array([[ 0.59395058, -0.41273345,  1.50392381, ...,  1.1672034 ,
        -1.50732963,  1.08472557],
       [ 0.2021896 ,  0.37441634, -0.18880047, ..., -0.39566024,
         1.41465051,  1.22601069],
       [-1.079044  , -0.31374544, -0.88463426, ..., -1.43849538,
         0.65182081, -1.6821675 ],
       ...,
       [ 0.94782488, -1.66372653, -1.65391963, ...,  0.12639128,
         0.57344494,  1.31934985],
       [-1.1202346 ,  0.19397855, -0.2378051 , ...,  0.79408717,
        -1.36232268, -0.80197116],
       [-1.37764025,  1.51186671,  0.28265058, ..., -0.91749729,
         0.00295027,  1.18902334]])

Model Training & Evaluation




Using Random Forest

In [10]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
model_rand = RandomForestClassifier(random_state=1)
model_rand.fit(x_train, y_train)
pred_rand = model_rand.predict(x_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [11]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
# CONFUSION MATRIX
cnf_mat = confusion_matrix(y_test, pred_rand, labels=['stable', 'unstable'])
print(cnf_mat) 

[[ 625   87]
 [  55 1233]]


In [12]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_rand), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_rand, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_rand, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_rand, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_rand, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_rand, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_rand, pos_label='unstable')))

Accuracy score 0.929
Precision score for 'stable' 0.919
Precision score for 'unstable' 0.934
Recall score for 'stable' 0.878
Recall score for 'unstable' 0.957
F1 score for 'stable' 0.898
F1 score for 'unstable' 0.946


In [13]:
# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_rand))

              precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



Using Extra Trees 

In [14]:
# Extra Trees Classifier
model_ext = ExtraTreesClassifier(random_state=1)
model_ext.fit(x_train, y_train)
pred_ext = model_ext.predict(x_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [15]:
# CONFUSION MATRIX
cnf_mat_ext = confusion_matrix(y_test, pred_ext, labels=['stable', 'unstable'])
print(cnf_mat_ext) 

[[ 606  106]
 [  38 1250]]


In [16]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_ext), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_ext, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_ext, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_ext, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_ext, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_ext, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_ext, pos_label='unstable')))

Accuracy score 0.928
Precision score for 'stable' 0.941
Precision score for 'unstable' 0.922
Recall score for 'stable' 0.851
Recall score for 'unstable' 0.97
F1 score for 'stable' 0.894
F1 score for 'unstable' 0.946


In [17]:
# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_ext))

              precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



Using XGBoost

In [18]:
# xgboost with random forest
from xgboost import XGBRFClassifier
model_xgbrf = XGBRFClassifier(random_state=1)
model_xgbrf.fit(x_train, y_train)
pred_xgbrf = model_xgbrf.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [19]:
# CONFUSION MATRIX
cnf_mat_xgbrf = confusion_matrix(y_test, pred_xgbrf, labels=['stable', 'unstable'])
print(cnf_mat_xgbrf) 

[[ 414  298]
 [  79 1209]]


In [20]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_xgbrf), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_xgbrf, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_xgbrf, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_xgbrf, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_xgbrf, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_xgbrf, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_xgbrf, pos_label='unstable')))

Accuracy score 0.8115
Precision score for 'stable' 0.84
Precision score for 'unstable' 0.802
Recall score for 'stable' 0.581
Recall score for 'unstable' 0.939
F1 score for 'stable' 0.687
F1 score for 'unstable' 0.865


In [21]:
# Classification report
print(classification_report(y_test, pred_xgbrf))

              precision    recall  f1-score   support

      stable       0.84      0.58      0.69       712
    unstable       0.80      0.94      0.87      1288

    accuracy                           0.81      2000
   macro avg       0.82      0.76      0.78      2000
weighted avg       0.82      0.81      0.80      2000



In [22]:
# xgboost using gradient boosting
from xgboost import XGBClassifier
model_xgb = XGBClassifier(random_state=1)
model_xgb.fit(x_train, y_train)
pred_xgb = model_xgb.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
# CONFUSION MATRIX
cnf_mat_xgb = confusion_matrix(y_test, pred_xgb, labels=['stable', 'unstable'])
print(cnf_mat_xgb) 

[[ 603  109]
 [  52 1236]]


In [24]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_xgb), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_xgb, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_xgb, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_xgb, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_xgb, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_xgb, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_xgb, pos_label='unstable')))

Accuracy score 0.9195
Precision score for 'stable' 0.921
Precision score for 'unstable' 0.919
Recall score for 'stable' 0.847
Recall score for 'unstable' 0.96
F1 score for 'stable' 0.882
F1 score for 'unstable' 0.939


In [25]:
# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_xgb))

              precision    recall  f1-score   support

      stable       0.92      0.85      0.88       712
    unstable       0.92      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



LightGBM Classifier

In [26]:
# lightgbm
from lightgbm import LGBMClassifier
model_light = LGBMClassifier(random_state=1)
model_light.fit(x_train, y_train)
pred_light = model_light.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
# CONFUSION MATRIX
cnf_mat_light = confusion_matrix(y_test, pred_light, labels=['unstable', 'stable'])
print(cnf_mat_light) 

[[1239   49]
 [  76  636]]


In [28]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_light), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_light, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_light, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_light, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_light, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_light, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_light, pos_label='unstable')))

Accuracy score 0.9375
Precision score for 'stable' 0.928
Precision score for 'unstable' 0.942
Recall score for 'stable' 0.893
Recall score for 'unstable' 0.962
F1 score for 'stable' 0.911
F1 score for 'unstable' 0.952


In [29]:
# Classification report
print(classification_report(y_test, pred_light))

              precision    recall  f1-score   support

      stable       0.93      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



Improving Extra Trees Model Using Randomized Search CV

In [30]:
# parameters
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 
hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}

In [31]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(model_ext, hyperparameter_grid, cv=5, n_iter=10, n_jobs=-1, scoring='accuracy', verbose=1, random_state=1)
search = clf.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.5min finished
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:739: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


In [32]:
#checking for the best parameter for the model
search.best_params_.values()

dict_values([1000, 2, 8, None])

In [33]:
# experimenting with this parameter to test the model's performance
tree_param = ExtraTreesClassifier(n_estimators=1000, min_samples_split=2, 
                                 min_samples_leaf=8, max_features=None, random_state=1)
tree_param.fit(x_train, y_train)
tree_param_pred = tree_param.predict(x_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [34]:
# CONFUSION MATRIX
cnf_mat_newxt = confusion_matrix(y_test, tree_param_pred, labels=['stable', 'unstable'])
print(cnf_mat_newxt) 

[[ 619   93]
 [  53 1235]]


In [35]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, tree_param_pred), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, tree_param_pred, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, tree_param_pred, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, tree_param_pred, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, tree_param_pred, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, tree_param_pred, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, tree_param_pred, pos_label='unstable')))


Accuracy score 0.927
Precision score for 'stable' 0.921
Precision score for 'unstable' 0.93
Recall score for 'stable' 0.869
Recall score for 'unstable' 0.959
F1 score for 'stable' 0.895
F1 score for 'unstable' 0.944


In [36]:
# Classification report
print(classification_report(y_test, tree_param_pred))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [37]:
tree_param.feature_importances_

array([0.13723979, 0.14050787, 0.1346805 , 0.13541662, 0.00368361,
       0.0053368 , 0.00542927, 0.0049625 , 0.10256224, 0.1075776 ,
       0.11306257, 0.10954062])

In [38]:
# showing the features in order of importance
sorted(zip(tree_param.feature_importances_, df.drop('stabf', axis=1).columns), reverse=True)

[(0.14050787123292582, 'tau2'),
 (0.13723978831645356, 'tau1'),
 (0.13541662265504284, 'tau4'),
 (0.13468049625184006, 'tau3'),
 (0.1130625748200639, 'g3'),
 (0.10954061786399034, 'g4'),
 (0.10757760496355806, 'g2'),
 (0.10256224382786308, 'g1'),
 (0.0054292680802320815, 'p3'),
 (0.0053368014620138494, 'p2'),
 (0.004962501777389839, 'p4'),
 (0.0036836087486265406, 'p1')]

In [39]:
# auc score
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score
mod_prob = tree_param.predict_proba(x_test)
mod_prob = mod_prob[:, 1]
auc = roc_auc_score(y_test, mod_prob)
print('Extra trees with hyperparams tuning auc score: %.3f' % (auc))

Extra trees with hyperparams tuning auc score: 0.984
